// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // For migrations use the session-mode pooler (port 5432), not the transaction pooler (port 6543).
    // Run: $env:DATABASE_URL = "<pooler-host>:5432/postgres"; npx prisma migrate deploy
  },
});
